### ISSUE TITLE
第一批 shame list

### ISSUE THREAD

**Issue by amio** [cnodejs/github-shame-list#1]
手动整理的 https://zhuanlan.zhihu.com/p/37550198

iamzfj007
mengxiaof
wangkai000
zc-GGboy
blg1987
PJing
CrazyVirusss
shanjie001
Nimor123
eds
shenzhenjinma

**Comment by Jesonhu** [comment]
如果真的这些人是前端确实很羞愧的。但是这些人的确是前端吗，大部分在github没有记录，像是水军

**Comment by amio** [comment]
本来这些都是 GitHub 账号的，现在很多被删（被禁）了。GH 管理效率很高

**Comment by netfishx** [comment]
Eminem-liuzi  https://github.com/ry/deno/issues/66 别再更了,老子学不动了,头发都快掉完了!!
LoWangl https://github.com/ry/deno/issues/67 别再更了,老子快学不玩了,在更就要猝死了
